word_collection = {
    "Places": [
        "Bangalore",
        "Delhi",
        "Itanagar",
        "Chennai",
        "Hyderabad",
        "Thiruvananthapuram",
        "Mumbai",
        "Aizwal",
        "Jodhpur",
        "Gandinagar",
        "Jaipur",
        "Srinagar",
        "Shimla",
        "Chandigarh",
        "Patna",
        "Allahabad",
        "Varanasi",
        "Himalaya",
        "Dispur",
        "Panaji",
    ],
    "Personalities": [
        "Aryabhata",
        "Issac Newton",
        "Albert Einstein",
        "Pythagorus",
        "Archimedes",
        "Leonardo Da Vinci",
        "APJ Abdul Kalam",
        "Socrates",
        "Subhash Chandra Bose",
        "Steve Jobs",
        "Bill Gates",
        "Larry Page",
        "Nikola Tesla",
        "Benjamin Franklin",
        "George Washington",
        "Abraham Lincoln",
        "Pablo Picasso",
        "Mukesh Ambani",
        "John D Rockefeller",
        "Narendra Modi",
    ],
    "Games": [
        "Minecraft",
        "God of War",
        "Call of Duty",
        "Prince of Persia",
        "Far Cry",
        "Rainbow Siege",
        "Roblox",
        "Fortnite",
        "PUBG",
        "Uncharted",
        "GTA San Andreas",
        "Asphalt",
        "FIFA",
        "Among Us",
        "League of Legends",
        "Red Dead Redemption",
        "Halo",
        "Super Mario",
        "Watchdogs",
        "Need for Speed",
    ],
    "Sports": [
        "Hockey",
        "Cricket",
        "Football",
        "Badminton",
        "Basketball",
        "Baseball",
        "Volleyball",
        "Lawn Tennis",
        "Bowling",
        "Rugby",
        "Throwball",
        "Grand Prix",
        "Archery",
        "Athletics",
        "Gymnastics",
        "Wrestling",
        "Kabaddi",
        "Swimming",
        "Golf",
        "Table Tennis",
    ],
    "Brands": [
        "Nike",
        "Adidas",
        "Puma",
        "Under Armour",
        "OPPO",
        "ASUS",
        "One Plus",
        "Apple",
        "Realme",
        "Samsung",
        "VIVO",
        "Walmart",
        "Amazon",
        "Nokia",
        "Motorola",
        "Flipkart",
        "Dell",
        "LG",
        "Hewlett Packard",
        "ITC",
    ],
    "Cars": [
        "Lamborghini",
        "Ferrari",
        "BMW",
        "Ford",
        "Mercedes Benz",
        "Bugatti",
        "Koenigsegg",
        "Pagani",
        "Porsche",
        "Aston Martin",
        "Maserati",
        "Bentley",
        "Rolls Royce",
        "JEEP",
        "Volkswagon",
        "Audi",
        "Chevrolet",
        "Mini Cooper",
        "Renault",
        "Skoda",
    ],
}
