word_collection = {
    "Places": [
        "Bangalore",
        "Delhi",
        "Itanagar",
        "Chennai",
        "Hyderabad",
        "Thiruvananthapuram",
        "Mumbai",
        "Aizawl",
        "Jodhpur",
        "Gandhinagar",
        "Jaipur",
        "Srinagar",
        "Shimla",
        "Chandigarh",
        "Patna",
        "Allahabad",
        "Varanasi",
        "Himalaya",
        "Dispur",
        "Panaji",
    ],
    "Personalities": [
        "Aryabhata",
        "Issac Newton",
        "Albert Einstein",
        "Pythagorus",
        "Archimedes",
        "Leonardo Da Vinci",
        "APJ Abdul Kalam",
        "Socrates",
        "Subhash Chandra Bose",
        "Steve Jobs",
        "Bill Gates",
        "Larry Page",
        "Nikola Tesla",
        "Benjamin Franklin",
        "George Washington",
        "Abraham Lincoln",
        "Pablo Picasso",
        "Mukesh Ambani",
        "John D Rockefeller",
        "Narendra Modi",
        "Donald Trump",
    ],
    "Games": [
        "Minecraft",
        "God of War",
        "Call of Duty",
        "Prince of Persia",
        "Far Cry",
        "Rainbow Siege",
        "Roblox",
        "Fortnite",
        "PUBG",
        "Uncharted",
        "GTA San Andreas",
        "Asphalt",
        "FIFA",
        "Among Us",
        "League of Legends",
        "Red Dead Redemption",
        "Halo",
        "Super Mario",
        "Watchdogs",
        "Need for Speed",
    ],
    "Sports": [
        "Hockey",
        "Cricket",
        "Football",
        "Badminton",
        "Basketball",
        "Baseball",
        "Volleyball",
        "Lawn Tennis",
        "Bowling",
        "Rugby",
        "Throwball",
        "Fencing",
        "Archery",
        "Athletics",
        "Gymnastics",
        "Wrestling",
        "Kabaddi",
        "Swimming",
        "Golf",
        "Table Tennis",
    ],
    "Brands": [
        "Nike",
        "Adidas",
        "Puma",
        "Under Armour",
        "Oppo",
        "Asus",
        "One Plus",
        "Apple",
        "Realme",
        "Samsung",
        "Vivo",
        "Walmart",
        "Amazon",
        "Nokia",
        "Motorola",
        "Flipkart",
        "Dell",
        "Kipsta",
        "Hewlett Packard",
        "Casio",
    ],
    "Cars": [
        "Lamborghini",
        "Ferrari",
        "BMW",
        "Ford",
        "Mercedes Benz",
        "Bugatti",
        "Koenigsegg",
        "Pagani",
        "Porsche",
        "Aston Martin",
        "Maserati",
        "Bentley",
        "Rolls Royce",
        "Jeep",
        "Volkswagon",
        "Audi",
        "Chevrolet",
        "Mini Cooper",
        "Renault",
        "Skoda",
    ],
    "Fruits & Veggies": [
        "Pomegranate",
        "Cauliflower",
        "Broccoli",
        "Blueberries",
        "Beetroot",
        "Sweet Potato",
        "Watermelon",
        "Muskmelon",
        "Avocado",
        "Cucumber",
        "Eggplant",
        "Spinach",
        "Lettuce",
        "Ridge Gourd",
        "Bitter Gourd",
        "Spring Onion",
    ],
    "Sportsperson": [
        "Sachin Tendulkar",
        "Virat Kohli",
        "Mithali Raj",
        "Rahul Dravid",
        "Sunil Chettri",
        "Leander Paes",
        "Dipa Karmakar",
        "Hima Das",
        "Geeta Phogat",
        "Saina Nehwal",
        "Milkha Singh",
        "Abhinav Bindra",
        "Pankaj Advani",
    ],
        "Countries": [
        "Saudi Arabia",
        "India",
        "Switzerland",
        "United Kingdom",
        "England",
        "Norway",
        "Denmark",
        "Mexico",
        "Afghanistan",
        "Kazakhstan",
        "Germany",
        "Argentina",
        "Mauritius",
        "Malaysia",
        "Czech Republic",
        "Canada",
        "Ethopia",
        "Australia",
        "Finland",
        "Turkey",
        "Egypt",
    ],
}
